//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        public int Id { get; set; }
        public int LandPropertiyID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal MoneyRecieved { get; set; }
    
        public virtual LandProperty LandProperty { get; set; }
    }
}
